services:
  # node:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=roundforest
  #   depends_on:
  #     - db
  db:
    container_name: postgres_roundforest
    ports:
      - "7000:5432"
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=roundforest
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
